#!/bin/sh
webpack --devtool source-map

node_modules/.bin/uglifyjs dist/exploder.js \
  --output dist/exploder.min.js \
  --source-map dist/exploder.min.map \
  --source-map-url exploder.min.map \
  --compress warnings=false
